### PR TITLE
Moving to Hooks

### PR DESCRIPTION
**Pull request by Youngestdev**
Since React 16.8.2 officially supports hooks, I thought perhaps I could experiment it by rewriting this wonderful package form class components into hooks. Four (4) tests are currently failing as the tests are linked to the class component lifecycle from the use of `.prototype`.

But, I can't fix it since I don't write tests. Lmk what can be done here.

cc @paradoxxxzero @MiroslavPetrik @ooade

### CODE REVIEW

**Comment by ooade** [comment]
@Youngestdev Please check out to a new branch. And as well pull the beta branch as some things have changed. 

Thanks :+1:

**Comment by ooade** [comment]
Once it's done, feel free to send in a PR again

**Comment by Youngestdev** [comment]
Hopefully.

On Feb 23, 2019 00:29, "Ademola ⚡️" <notifications@github.com> wrote:

Once it's done, feel free to send in a PR again

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ooade/react-rough/pull/132#issuecomment-466584281>, or mute
the thread

**Comment by ooade** [comment]
@Youngestdev https://www.reddit.com/r/reactjs/comments/avx34g/dont_let_the_react_team_control_you_use_hooks_in/

**Pull request closed without merging**
