### PR TITLE
Fix node update

### PR DESCRIPTION
**Pull request by ashinzekene**
😄

### CODE REVIEW

**Comment by ooade** [comment]
I appreciate all of these. Thanks man!!!!

Passing `config={{ options: { roughness: number('roughness', 0) } }}` from Storybook, to `ReactRough` or `ReactRoughSvg` doesn't get updated mainly because the config get plugged in at the render props.

**Comment by ashinzekene** [comment]
🤔  I actually thought of this too. There might be a catch though. The component themselves accept their own configs.

```jsx
	<Rectangle
		x={number('x', 15)}
		y={number('y', 15)}
		width={number('width', 80)}
		fill={color('color', 'red')}
		height={number('height', 80)}
		roughness={number('roughnessRect', 80)}
	/>
```
It won't be nice to overwrite their own config with the parent's config. I don't know if there's a way to know which config was used in drawing the shape....

**Comment by ooade** [comment]
> 🤔 I actually thought of this too. There might be a catch though. The component themselves accept their own configs.
> 
> ```js-jsx
> 	<Rectangle
> 		x={number('x', 15)}
> 		y={number('y', 15)}
> 		width={number('width', 80)}
> 		fill={color('color', 'red')}
> 		height={number('height', 80)}
> 		roughness={number('roughnessRect', 80)}
> 	/>
> ```
> 
> It won't be nice to overwrite their own config with the parent's config. I don't know if there's a way to know which config was used in drawing the shape....

Yeah, you're right. But, it won't be overwriting their own config. One it uses a different thing from what exists in the global config, it should just take that.

**Comment by ashinzekene** [comment]
I dint get

> One it uses a different thing from what exists in the global config, it should just take that.

**Comment by ooade** [comment]
> I dint get
> 
> > One it uses a different thing from what exists in the global config, it should just take that.

The config passed to ReactRough should not in any way be related to the one passed individually

**Comment by ooade** [comment]
Merging as I'd update it on my end. Thanks a lot!

**Comment by ashinzekene** [comment]
Okay . I tried some stuff but didn't work 😄

**Comment by ooade** [comment]
Hahaha. I had to kinda do a rewrite to make it work 😅

**Comment by ashinzekene** [comment]
😄

**Pull request merged**
